language: perl
sudo: false

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_install:
  - cpanm --quiet --notest --skip-satisfied git://github.com/codecov/codecov-perl.git
  - cover -delete
script:
  - perl Build.PL
  - ./Build build
  - cover -test -report codecov
